[[constraint]]
  name = "k8s.io/utils"
  branch = "master"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  branch = "v2"

[[constraint]]
  name = "github.com/oracle/oci-go-sdk"
  version = "v1.0.0"

[[constraint]]
  version = "kubernetes-1.11.1"
  name = "k8s.io/apimachinery"

[[constraint]]
  name = "k8s.io/client-go"
  version = "~8.0"
