[[constraint]]
  name = "k8s.io/utils"
  branch = "master"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "master"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  branch = "v2"

[[constraint]]
  name = "github.com/oracle/oci-go-sdk"
  version = "<=1.3.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "v1.2.1"